// <auto-generated />
using System;
using System.Collections.Generic;
using MediSearch.Infrastructure.Persistence.Shared.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MediSearch.Infrastructure.Persistence.Shared.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260912130000_NormalizeUniqueTextColumns")]
    partial class NormalizeUniqueTextColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.InboxState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("Consumed")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("uuid")
                        .HasColumnName("consumer_id");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiration_time");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("last_sequence_number");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uuid")
                        .HasColumnName("lock_id");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<int>("ReceiveCount")
                        .HasColumnType("integer")
                        .HasColumnName("receive_count");

                    b.Property<DateTime>("Received")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.HasKey("Id")
                        .HasName("pk_inbox_state");

                    b.HasAlternateKey("MessageId", "ConsumerId")
                        .HasName("ak_inbox_state_message_id_consumer_id");

                    b.HasIndex("Delivered")
                        .HasDatabaseName("ix_inbox_state_delivered");

                    b.ToTable("inbox_state", (string)null);
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.Property<long>("SequenceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("sequence_number");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SequenceNumber"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("content_type");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<string>("DestinationAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("destination_address");

                    b.Property<DateTime?>("EnqueueTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enqueue_time");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiration_time");

                    b.Property<string>("FaultAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("fault_address");

                    b.Property<string>("Headers")
                        .HasColumnType("text")
                        .HasColumnName("headers");

                    b.Property<Guid?>("InboxConsumerId")
                        .HasColumnType("uuid")
                        .HasColumnName("inbox_consumer_id");

                    b.Property<Guid?>("InboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("inbox_message_id");

                    b.Property<Guid?>("InitiatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("initiator_id");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_type");

                    b.Property<Guid?>("OutboxId")
                        .HasColumnType("uuid")
                        .HasColumnName("outbox_id");

                    b.Property<string>("Properties")
                        .HasColumnType("text")
                        .HasColumnName("properties");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<string>("ResponseAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("response_address");

                    b.Property<DateTime>("SentTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_time");

                    b.Property<string>("SourceAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("source_address");

                    b.HasKey("SequenceNumber")
                        .HasName("pk_outbox_message");

                    b.HasIndex("EnqueueTime")
                        .HasDatabaseName("ix_outbox_message_enqueue_time");

                    b.HasIndex("ExpirationTime")
                        .HasDatabaseName("ix_outbox_message_expiration_time");

                    b.HasIndex("OutboxId", "SequenceNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_outbox_message_outbox_id_sequence_number");

                    b.HasIndex("InboxMessageId", "InboxConsumerId", "SequenceNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_outbox_message_inbox_message_id_inbox_consumer_id_sequence_");

                    b.ToTable("outbox_message", (string)null);
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxState", b =>
                {
                    b.Property<Guid>("OutboxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("outbox_id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("last_sequence_number");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uuid")
                        .HasColumnName("lock_id");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.HasKey("OutboxId")
                        .HasName("pk_outbox_state");

                    b.HasIndex("Created")
                        .HasDatabaseName("ix_outbox_state_created");

                    b.ToTable("outbox_state", (string)null);
                });

            modelBuilder.Entity("MediSearch.Core.Domain.Catalog.Comments.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<Guid?>("ParentCommentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_comment_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_comments");

                    b.HasIndex("ParentCommentId")
                        .HasDatabaseName("ix_comments_parent_comment_id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_comments_product_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_comments_user_id");

                    b.HasIndex("ParentCommentId", "CreatedAt")
                        .HasDatabaseName("ix_comments_parent_comment_id_created_at");

                    b.HasIndex("ProductId", "CreatedAt")
                        .HasDatabaseName("ix_comments_product_id_created_at");

                    b.ToTable("comments", (string)null);
                });

            modelBuilder.Entity("MediSearch.Core.Domain.Catalog.ProductClassifications.ClassificationCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClassificationId")
                        .HasColumnType("uuid")
                        .HasColumnName("classification_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Name", "MediSearch.Core.Domain.Catalog.ProductClassifications.ClassificationCategory.Name#Name", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Normalized")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("character varying(150)")
                                .HasColumnName("normalized_name");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("character varying(150)")
                                .HasColumnName("name");
                        });

                    b.HasKey("Id")
                        .HasName("pk_classification_categories");

                    b.ToTable("classification_categories", (string)null);
                });

            modelBuilder.Entity("MediSearch.Core.Domain.Catalog.ProductClassifications.ProductClassification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Name", "MediSearch.Core.Domain.Catalog.ProductClassifications.ProductClassification.Name#Name", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Normalized")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("character varying(150)")
                                .HasColumnName("normalized_name");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("character varying(150)")
                                .HasColumnName("name");
                        });

                    b.HasKey("Id")
                        .HasName("pk_product_classifications");

                    b.ToTable("product_classifications", (string)null);
                });

            modelBuilder.Entity("MediSearch.Core.Domain.Catalog.Products.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClassificationId")
                        .HasColumnType("uuid")
                        .HasColumnName("classification_id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Price", "MediSearch.Core.Domain.Catalog.Products.Product.Price#Price", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<double>("Amount")
                                .HasColumnType("double precision")
                                .HasColumnName("price_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("price_currency");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Name", "MediSearch.Core.Domain.Catalog.Products.Product.Name#ProductName", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Normalized")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("normalized_name");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("name");
                        });

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("ClassificationId")
                        .HasDatabaseName("ix_products_classification_id");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_products_company_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_products_created_at");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("MediSearch.Core.Domain.Chat.ChatRooms.ChatRoom", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<Guid?>("LastMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_message_id");

                    b.Property<DateTimeOffset>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.HasKey("Id")
                        .HasName("pk_chat_rooms");

                    b.HasIndex("LastMessageId")
                        .IsUnique()
                        .HasDatabaseName("ix_chat_rooms_last_message_id");

                    b.ToTable("chat_rooms", (string)null);
                });

            modelBuilder.Entity("MediSearch.Core.Domain.Chat.Messages.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChatRoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("chat_room_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<DateTimeOffset>("MessageSentDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("message_sent_date");

                    b.Property<string>("TextContent")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("text_content");

                    b.HasKey("Id")
                        .HasName("pk_messages");

                    b.HasIndex("ChatRoomId")
                        .HasDatabaseName("ix_messages_chat_room_id");

                    b.HasIndex("ChatRoomId", "MessageSentDate")
                        .HasDatabaseName("ix_messages_chat_room_id_message_sent_date");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("MediSearch.Core.Domain.Companies.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CeoName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("ceo_name");

                    b.Property<int>("CompanyTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("company_type_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Facebook")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("facebook");

                    b.Property<string>("ImageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_key");

                    b.Property<string>("Instagram")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("instagram");

                    b.Property<DateTimeOffset>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("phone_number");

                    b.Property<string>("Twitter")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("twitter");

                    b.Property<string>("Website")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("website");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Location", "MediSearch.Core.Domain.Companies.Company.Location#Location", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("address");

                            b1.Property<string>("Municipality")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("municipality");

                            b1.Property<string>("Province")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("province");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Email", "MediSearch.Core.Domain.Companies.Company.Email#Email", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasMaxLength(320)
                                .HasColumnType("character varying(320)")
                                .HasColumnName("email");

                            b1.Property<string>("Normalized")
                                .IsRequired()
                                .HasMaxLength(320)
                                .HasColumnType("character varying(320)")
                                .HasColumnName("normalized_email");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Name", "MediSearch.Core.Domain.Companies.Company.Name#CompanyName", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Normalized")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("normalized_name");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("name");
                        });

                    b.HasKey("Id")
                        .HasName("pk_companies");

                    b.HasIndex("CompanyTypeId")
                        .HasDatabaseName("ix_companies_company_type_id");

                    b.HasIndex("CompanyTypeId", "CreatedAt")
                        .HasDatabaseName("ix_companies_company_type_id_created_at");

                    b.ToTable("companies", (string)null);
                });

            modelBuilder.Entity("MediSearch.Core.Domain.Companies.CompanyType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_company_types");

                    b.ToTable("company_types", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Pharmacy"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Laboratory"
                        });
                });

            modelBuilder.Entity("MediSearch.Core.Domain.Favorites.CompanyFavorites.CompanyFavorite", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.HasKey("Id")
                        .HasName("pk_company_favorites");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_company_favorites_company_id");

                    b.ToTable("company_favorites", (string)null);
                });

            modelBuilder.Entity("MediSearch.Core.Domain.Favorites.ProductFavorites.ProductFavorite", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.HasKey("Id")
                        .HasName("pk_product_favorites");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_product_favorites_product_id");

                    b.ToTable("product_favorites", (string)null);
                });

            modelBuilder.Entity("MediSearch.Core.Domain.SharedKernel.Enums.AgentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_agent_types");

                    b.ToTable("agent_types", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "User"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Company"
                        });
                });

            modelBuilder.Entity("MediSearch.Core.Domain.Users.AccessControl.Permission", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.HasKey("Code")
                        .HasName("pk_permissions");

                    b.ToTable("permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "company:update"
                        },
                        new
                        {
                            Code = "company:add-user"
                        },
                        new
                        {
                            Code = "company:remove-user"
                        },
                        new
                        {
                            Code = "company:read-dashboard"
                        },
                        new
                        {
                            Code = "company-favorite:add"
                        },
                        new
                        {
                            Code = "company-favorite:remove"
                        },
                        new
                        {
                            Code = "product-favorite:add"
                        },
                        new
                        {
                            Code = "product-favorite:remove"
                        },
                        new
                        {
                            Code = "product:add"
                        },
                        new
                        {
                            Code = "product:update"
                        },
                        new
                        {
                            Code = "product:remove"
                        },
                        new
                        {
                            Code = "user:remove"
                        },
                        new
                        {
                            Code = "company:remove"
                        },
                        new
                        {
                            Code = "classification-category:create"
                        },
                        new
                        {
                            Code = "classification-category:update"
                        },
                        new
                        {
                            Code = "classification-category:delete"
                        },
                        new
                        {
                            Code = "product-classification:create"
                        },
                        new
                        {
                            Code = "product-classification:update"
                        },
                        new
                        {
                            Code = "product-classification:delete"
                        });
                });

            modelBuilder.Entity("MediSearch.Core.Domain.Users.AccessControl.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_name");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "SystemAdmin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "CompanyOwner"
                        },
                        new
                        {
                            Id = 3,
                            Name = "CompanyManager"
                        },
                        new
                        {
                            Id = 4,
                            Name = "CompanyMember"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Client"
                        });
                });

            modelBuilder.Entity("MediSearch.Core.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_id");

                    b.Property<DateTimeOffset>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_at");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("phone_number");

                    b.Property<string>("ProfileImageKey")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("profile_image_key");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "FullName", "MediSearch.Core.Domain.Users.User.FullName#FullName", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("first_name");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("last_name");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Location", "MediSearch.Core.Domain.Users.User.Location#Location", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("address");

                            b1.Property<string>("Municipality")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("municipality");

                            b1.Property<string>("Province")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("province");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Username", "MediSearch.Core.Domain.Users.User.Username#Username", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Normalized")
                                .IsRequired()
                                .HasMaxLength(15)
                                .HasColumnType("character varying(15)")
                                .HasColumnName("normalized_username");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(15)
                                .HasColumnType("character varying(15)")
                                .HasColumnName("username");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Email", "MediSearch.Core.Domain.Users.User.Email#Email", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasMaxLength(320)
                                .HasColumnType("character varying(320)")
                                .HasColumnName("email");

                            b1.Property<string>("Normalized")
                                .IsRequired()
                                .HasMaxLength(320)
                                .HasColumnType("character varying(320)")
                                .HasColumnName("normalized_email");
                        });

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_users_company_id")
                        .HasFilter("company_id IS NOT NULL");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_external_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("PermissionRole", b =>
                {
                    b.Property<string>("PermissionCode")
                        .HasColumnType("character varying(100)")
                        .HasColumnName("permission_code");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("PermissionCode", "RoleId")
                        .HasName("pk_role_permissions");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_role_permissions_role_id");

                    b.HasIndex("PermissionCode", "RoleId")
                        .HasDatabaseName("ix_role_permissions_permission_code_role_id");

                    b.ToTable("role_permissions", (string)null);

                    b.HasData(
                        new
                        {
                            PermissionCode = "classification-category:create",
                            RoleId = 1
                        },
                        new
                        {
                            PermissionCode = "classification-category:update",
                            RoleId = 1
                        },
                        new
                        {
                            PermissionCode = "classification-category:delete",
                            RoleId = 1
                        },
                        new
                        {
                            PermissionCode = "product-classification:create",
                            RoleId = 1
                        },
                        new
                        {
                            PermissionCode = "product-classification:update",
                            RoleId = 1
                        },
                        new
                        {
                            PermissionCode = "product-classification:delete",
                            RoleId = 1
                        },
                        new
                        {
                            PermissionCode = "user:remove",
                            RoleId = 1
                        },
                        new
                        {
                            PermissionCode = "company:remove",
                            RoleId = 1
                        },
                        new
                        {
                            PermissionCode = "company:update",
                            RoleId = 2
                        },
                        new
                        {
                            PermissionCode = "company:add-user",
                            RoleId = 2
                        },
                        new
                        {
                            PermissionCode = "company:remove-user",
                            RoleId = 2
                        },
                        new
                        {
                            PermissionCode = "company:read-dashboard",
                            RoleId = 2
                        },
                        new
                        {
                            PermissionCode = "company-favorite:add",
                            RoleId = 2
                        },
                        new
                        {
                            PermissionCode = "company-favorite:remove",
                            RoleId = 2
                        },
                        new
                        {
                            PermissionCode = "product-favorite:add",
                            RoleId = 2
                        },
                        new
                        {
                            PermissionCode = "product-favorite:remove",
                            RoleId = 2
                        },
                        new
                        {
                            PermissionCode = "product:add",
                            RoleId = 2
                        },
                        new
                        {
                            PermissionCode = "product:update",
                            RoleId = 2
                        },
                        new
                        {
                            PermissionCode = "product:remove",
                            RoleId = 2
                        },
                        new
                        {
                            PermissionCode = "company:remove",
                            RoleId = 2
                        },
                        new
                        {
                            PermissionCode = "company:add-user",
                            RoleId = 3
                        },
                        new
                        {
                            PermissionCode = "company:remove-user",
                            RoleId = 3
                        },
                        new
                        {
                            PermissionCode = "company:read-dashboard",
                            RoleId = 3
                        },
                        new
                        {
                            PermissionCode = "company-favorite:add",
                            RoleId = 3
                        },
                        new
                        {
                            PermissionCode = "company-favorite:remove",
                            RoleId = 3
                        },
                        new
                        {
                            PermissionCode = "product-favorite:add",
                            RoleId = 3
                        },
                        new
                        {
                            PermissionCode = "product-favorite:remove",
                            RoleId = 3
                        },
                        new
                        {
                            PermissionCode = "product:add",
                            RoleId = 3
                        },
                        new
                        {
                            PermissionCode = "product:update",
                            RoleId = 3
                        },
                        new
                        {
                            PermissionCode = "product:remove",
                            RoleId = 3
                        },
                        new
                        {
                            PermissionCode = "company:read-dashboard",
                            RoleId = 4
                        },
                        new
                        {
                            PermissionCode = "product:add",
                            RoleId = 4
                        },
                        new
                        {
                            PermissionCode = "product:update",
                            RoleId = 4
                        },
                        new
                        {
                            PermissionCode = "product:remove",
                            RoleId = 4
                        },
                        new
                        {
                            PermissionCode = "company-favorite:add",
                            RoleId = 5
                        },
                        new
                        {
                            PermissionCode = "company-favorite:remove",
                            RoleId = 5
                        },
                        new
                        {
                            PermissionCode = "product-favorite:add",
                            RoleId = 5
                        },
                        new
                        {
                            PermissionCode = "product-favorite:remove",
                            RoleId = 5
                        });
                });

            modelBuilder.Entity("user_roles", b =>
                {
                    b.Property<Guid>("user_id")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("role_id")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("user_id", "role_id")
                        .HasName("pk_user_roles");

                    b.HasIndex("role_id", "user_id")
                        .HasDatabaseName("ix_user_roles_role_id_user_id");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.OutboxState", null)
                        .WithMany()
                        .HasForeignKey("OutboxId")
                        .HasConstraintName("fk_outbox_message_outbox_state_outbox_id");

                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.InboxState", null)
                        .WithMany()
                        .HasForeignKey("InboxMessageId", "InboxConsumerId")
                        .HasPrincipalKey("MessageId", "ConsumerId")
                        .HasConstraintName("fk_outbox_message_inbox_state_inbox_message_id_inbox_consumer_");
                });

            modelBuilder.Entity("MediSearch.Core.Domain.Catalog.Comments.Comment", b =>
                {
                    b.HasOne("MediSearch.Core.Domain.Catalog.Comments.Comment", null)
                        .WithMany()
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_comments_comments_parent_comment_id");

                    b.HasOne("MediSearch.Core.Domain.Catalog.Products.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comments_products_product_id");

                    b.HasOne("MediSearch.Core.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comments_users_user_id");
                });

            modelBuilder.Entity("MediSearch.Core.Domain.Catalog.ProductClassifications.ClassificationCategory", b =>
                {
                    b.HasOne("MediSearch.Core.Domain.Catalog.ProductClassifications.ProductClassification", null)
                        .WithMany("Categories")
                        .HasForeignKey("ClassificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_classification_categories_product_classifications_classific");
                });

            modelBuilder.Entity("MediSearch.Core.Domain.Catalog.Products.Product", b =>
                {
                    b.HasOne("MediSearch.Core.Domain.Catalog.ProductClassifications.ProductClassification", null)
                        .WithMany()
                        .HasForeignKey("ClassificationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_products_product_classifications_classification_id");

                    b.HasOne("MediSearch.Core.Domain.Companies.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_products_companies_company_id");

                    b.OwnsMany("MediSearch.Core.Domain.SharedKernel.ValueObjects.AssetKey", "ImageKeys", b1 =>
                        {
                            b1.Property<int>("id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("id"));

                            b1.Property<string>("Key")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("image_key");

                            b1.Property<int>("ordinal")
                                .HasColumnType("integer")
                                .HasColumnName("ordinal");

                            b1.Property<Guid>("product_id")
                                .HasColumnType("uuid")
                                .HasColumnName("product_id");

                            b1.HasKey("id")
                                .HasName("pk_product_images");

                            b1.HasIndex("product_id", "ordinal")
                                .HasDatabaseName("ix_product_images_product_id_ordinal");

                            b1.ToTable("product_images", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("product_id")
                                .HasConstraintName("fk_product_images_products_product_id");
                        });

                    b.OwnsMany("MediSearch.Core.Domain.SharedKernel.ValueObjects.EntityId<MediSearch.Core.Domain.Catalog.ProductClassifications.ClassificationCategory>", "CategoryIds", b1 =>
                        {
                            b1.Property<Guid>("product_id")
                                .HasColumnType("uuid")
                                .HasColumnName("product_id");

                            b1.Property<Guid>("Value")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("category_id");

                            b1.HasKey("product_id", "Value")
                                .HasName("pk_products_classification_categories");

                            b1.HasIndex("Value")
                                .HasDatabaseName("ix_products_classification_categories_category_id");

                            b1.ToTable("products_classification_categories", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("product_id")
                                .HasConstraintName("fk_products_classification_categories_products_product_id");
                        });

                    b.Navigation("CategoryIds");

                    b.Navigation("ImageKeys");
                });

            modelBuilder.Entity("MediSearch.Core.Domain.Chat.ChatRooms.ChatRoom", b =>
                {
                    b.HasOne("MediSearch.Core.Domain.Chat.Messages.Message", null)
                        .WithOne()
                        .HasForeignKey("MediSearch.Core.Domain.Chat.ChatRooms.ChatRoom", "LastMessageId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_chat_rooms_messages_last_message_id");

                    b.OwnsMany("MediSearch.Core.Domain.Chat.ChatRooms.ChatRoomParticipant", "Participants", b1 =>
                        {
                            b1.Property<int>("id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("id"));

                            b1.Property<DateTimeOffset?>("LastCheckedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("last_checked_at");

                            b1.Property<Guid?>("chat_room_id")
                                .HasColumnType("uuid")
                                .HasColumnName("chat_room_id");

                            b1.HasKey("id")
                                .HasName("pk_chat_room_participants");

                            b1.HasIndex("chat_room_id")
                                .HasDatabaseName("ix_chat_room_participants_chat_room_id");

                            b1.ToTable("chat_room_participants", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("chat_room_id")
                                .HasConstraintName("fk_chat_room_participants_chat_rooms_chat_room_id");

                            b1.OwnsOne("MediSearch.Core.Domain.SharedKernel.ValueObjects.Agent", "Agent", b2 =>
                                {
                                    b2.Property<int>("ChatRoomParticipantid")
                                        .HasColumnType("integer")
                                        .HasColumnName("id");

                                    b2.Property<Guid>("AgentId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("participant_id");

                                    b2.Property<int>("AgentTypeId")
                                        .HasColumnType("integer")
                                        .HasColumnName("participant_type_id");

                                    b2.HasKey("ChatRoomParticipantid");

                                    b2.HasIndex("AgentTypeId")
                                        .HasDatabaseName("ix_chat_room_participants_participant_type_id");

                                    b2.ToTable("chat_room_participants");

                                    b2.HasOne("MediSearch.Core.Domain.SharedKernel.Enums.AgentType", null)
                                        .WithMany()
                                        .HasForeignKey("AgentTypeId")
                                        .OnDelete(DeleteBehavior.Restrict)
                                        .IsRequired()
                                        .HasConstraintName("fk_chat_room_participants_agent_type_participant_type_id");

                                    b2.WithOwner()
                                        .HasForeignKey("ChatRoomParticipantid")
                                        .HasConstraintName("fk_chat_room_participants_chat_room_participants_id");
                                });

                            b1.Navigation("Agent")
                                .IsRequired();
                        });

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("MediSearch.Core.Domain.Chat.Messages.Message", b =>
                {
                    b.HasOne("MediSearch.Core.Domain.Chat.ChatRooms.ChatRoom", null)
                        .WithMany()
                        .HasForeignKey("ChatRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_messages_chat_rooms_chat_room_id");

                    b.OwnsOne("MediSearch.Core.Domain.SharedKernel.ValueObjects.Agent", "SenderAgent", b1 =>
                        {
                            b1.Property<Guid>("MessageId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid>("AgentId")
                                .HasColumnType("uuid")
                                .HasColumnName("sender_id");

                            b1.Property<int>("AgentTypeId")
                                .HasColumnType("integer")
                                .HasColumnName("sender_type_id");

                            b1.HasKey("MessageId");

                            b1.HasIndex("AgentTypeId")
                                .HasDatabaseName("ix_messages_sender_type_id");

                            b1.ToTable("messages");

                            b1.HasOne("MediSearch.Core.Domain.SharedKernel.Enums.AgentType", null)
                                .WithMany()
                                .HasForeignKey("AgentTypeId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired()
                                .HasConstraintName("fk_messages_agent_type_sender_type_id");

                            b1.WithOwner()
                                .HasForeignKey("MessageId")
                                .HasConstraintName("fk_messages_messages_id");
                        });

                    b.OwnsOne("MediSearch.Core.Domain.Chat.Messages.MessageMediaContent", "MediaContent", b1 =>
                        {
                            b1.Property<Guid>("MessageId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("AssetKey")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("media_content_asset_key");

                            b1.Property<string>("MediaType")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("media_content_type");

                            b1.HasKey("MessageId");

                            b1.ToTable("messages");

                            b1.WithOwner()
                                .HasForeignKey("MessageId")
                                .HasConstraintName("fk_messages_messages_id");
                        });

                    b.Navigation("MediaContent");

                    b.Navigation("SenderAgent")
                        .IsRequired();
                });

            modelBuilder.Entity("MediSearch.Core.Domain.Companies.Company", b =>
                {
                    b.HasOne("MediSearch.Core.Domain.Companies.CompanyType", null)
                        .WithMany()
                        .HasForeignKey("CompanyTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_companies_company_type_company_type_id");
                });

            modelBuilder.Entity("MediSearch.Core.Domain.Favorites.CompanyFavorites.CompanyFavorite", b =>
                {
                    b.HasOne("MediSearch.Core.Domain.Companies.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_company_favorites_companies_company_id");

                    b.OwnsOne("MediSearch.Core.Domain.SharedKernel.ValueObjects.Agent", "FavoriterAgent", b1 =>
                        {
                            b1.Property<Guid>("CompanyFavoriteId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid>("AgentId")
                                .HasColumnType("uuid")
                                .HasColumnName("favoriter_id");

                            b1.Property<int>("AgentTypeId")
                                .HasColumnType("integer")
                                .HasColumnName("favoriter_type_id");

                            b1.HasKey("CompanyFavoriteId");

                            b1.HasIndex("AgentTypeId")
                                .HasDatabaseName("ix_company_favorites_favoriter_type_id");

                            b1.ToTable("company_favorites");

                            b1.HasOne("MediSearch.Core.Domain.SharedKernel.Enums.AgentType", null)
                                .WithMany()
                                .HasForeignKey("AgentTypeId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired()
                                .HasConstraintName("fk_company_favorites_agent_type_favoriter_type_id");

                            b1.WithOwner()
                                .HasForeignKey("CompanyFavoriteId")
                                .HasConstraintName("fk_company_favorites_company_favorites_id");
                        });

                    b.Navigation("FavoriterAgent")
                        .IsRequired();
                });

            modelBuilder.Entity("MediSearch.Core.Domain.Favorites.ProductFavorites.ProductFavorite", b =>
                {
                    b.HasOne("MediSearch.Core.Domain.Catalog.Products.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_favorites_products_product_id");

                    b.OwnsOne("MediSearch.Core.Domain.SharedKernel.ValueObjects.Agent", "FavoriterAgent", b1 =>
                        {
                            b1.Property<Guid>("ProductFavoriteId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid>("AgentId")
                                .HasColumnType("uuid")
                                .HasColumnName("favoriter_id");

                            b1.Property<int>("AgentTypeId")
                                .HasColumnType("integer")
                                .HasColumnName("favoriter_type_id");

                            b1.HasKey("ProductFavoriteId");

                            b1.HasIndex("AgentTypeId")
                                .HasDatabaseName("ix_product_favorites_favoriter_type_id");

                            b1.ToTable("product_favorites");

                            b1.HasOne("MediSearch.Core.Domain.SharedKernel.Enums.AgentType", null)
                                .WithMany()
                                .HasForeignKey("AgentTypeId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired()
                                .HasConstraintName("fk_product_favorites_agent_type_favoriter_type_id");

                            b1.WithOwner()
                                .HasForeignKey("ProductFavoriteId")
                                .HasConstraintName("fk_product_favorites_product_favorites_id");
                        });

                    b.Navigation("FavoriterAgent")
                        .IsRequired();
                });

            modelBuilder.Entity("MediSearch.Core.Domain.Users.User", b =>
                {
                    b.HasOne("MediSearch.Core.Domain.Companies.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_users_companies_company_id");
                });

            modelBuilder.Entity("PermissionRole", b =>
                {
                    b.HasOne("MediSearch.Core.Domain.Users.AccessControl.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_permissions_permission_code");

                    b.HasOne("MediSearch.Core.Domain.Users.AccessControl.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_role_role_id");
                });

            modelBuilder.Entity("user_roles", b =>
                {
                    b.HasOne("MediSearch.Core.Domain.Users.AccessControl.Role", null)
                        .WithMany()
                        .HasForeignKey("role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_role_id");

                    b.HasOne("MediSearch.Core.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");
                });

            modelBuilder.Entity("MediSearch.Core.Domain.Catalog.ProductClassifications.ProductClassification", b =>
                {
                    b.Navigation("Categories");
                });
#pragma warning restore 612, 618
        }
    }
}
