<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>MediSearch.Core.Application</RootNamespace>
    <AssemblyName>MediSearch.Core.Application</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Mapster" />
    <PackageReference Include="MediatR" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MediSearch.Core.Domain\MediSearch.Core.Domain.csproj" />
  </ItemGroup>
</Project>
